### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by winston0410** [kumudkush/html-from-form-exercise#1]
Wrong usage of the `<label>`

https://github.com/kumudkush/html-from-form-exercise/blob/b39b1d9582b3c58cce7e1062437b6cd9379b429c/index.html#L53-L54

```html
<label for="agree">
           <input type = "radio" id="agree" name="agree" value="agree" checked="true">
I agree</label>
```

otherwise perfect

**Comment by kumudkush** [comment]
Thank you Hugo. Noted the usage of <label>
